version: "3.7"

services:
  jmj-bot:
    image: rg.fr-par.scw.cloud/indieco/jmj-bot
    restart: unless-stopped
    logging:
      driver: "json-file"
      options:
        max-file: "5"
        max-size: "10m"
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./logs:/bot/logs
    environment:
      DISCORD_TOKEN: ${DISCORD_TOKEN}