name: Build & publish container

on:
  workflow_dispatch:

env:
  REGISTRY: rg.fr-par.scw.cloud/indieco
  IMAGE_NAME: jmj-bot

jobs:
  setup-build-publish:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Log into registry ${{ env.REGISTRY }}
        uses: docker/login-action@v1
        with:
          registry: ${{ env.REGISTRY }}
          username: "nologin"
          password: ${{ secrets.SCW_SECRET_TOKEN }}

      - name: Build and push image
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
